s = 'ACTGCCTGTAGCACTTTGCAACGGAATATAAAGGGCTTGTTGGTTTGTACAATTTGTAAATATTTCCCCCACATCTCTGTAGCCTTTGACCGATTCGTCGGATAACGTCGCGCATCAGCGCTCCAGAAAAACACTGTAGGCTCGGTAAGCATTTACTGTGAACGGCGGGGTGAAAAGCAATGGCGAGTAACGATTCAGTTGTTCTGCAGCGATGGGTCTACGGATTATTCAGACCCAGAGGACCGTCGCTGGCCAGATTAGAGTTTCTTTGTTTAGCGTCGCTATCTTACGCTGATCATCGTTATGCCTCTTGGCATAGATAGTAATTCAACAGAATCAGGCAATAGGGTGATTGCAGTTCTCCCGCACGAAAGTAGAACTCCCTAGCATAATTTACGCCCTGTCGCGTCACGATACGACCAGCGGACCAGGAATCGGGCCTATTACTTAATATTTCATAACCTGAAGTTCGTGTCGGGTGGAGAGTGCCTAGACGTGCGTAGTACCAAGTGTTGTATCAATCTCCGGAAGGCACGACAATCACTTGATCAACATTAACGTGCCTCACACGTATAGACAAAGTATTAGGCGATACTTATGGCGATCGTTCGATAATACCACGTATGGACACCAGACAACGTTACCAACGATTTTCGGGGATTTCTAGCCCACCTTCGAACAACCCATTATCGGTATCGATCGCAGAACCTCCACGACACTACTCGATGACTAGGAAGCAGTCGCAGGGGACACTGATCAGCCTCGGGCGCGGCTATGCTATAATACAGCTTCACCATGAGCAGGGAGGCTACTGCTACAATGAACTCATGTACCATGGGAGATGTCACAG'
k = ""
for i in s:
    if i == 'C':
        k += 'G'
    elif i == 'G':
        k+= 'C'
    elif i == 'T':
        k+= 'A'
    elif i == 'A':
        k+= 'T'

k= k[::-1]
print (k)