s = "ATATTAAAGCGATGTAAGTGCAAGTTTTTAGTGGGCTTAGATTTATTCGAGAAGATGGTAGCGCCCCCACCCGGGGCCCTACTAATAACGCAGCATAGAAGAGTGACAAAAAGATAACACGAGCTATGCTTCACGCTGGATGACATCAGCATAATTCTATCCTCGCAACAGGGAGTATAGGGCTGTAGGTTACCGAGGGGTTTTACAGGGAGAGGACTGGCTGTACCGTAAATCATTGATTGATTTCTCTTATCTAAGTCTCGTAATGAGCTTTTGCTGTTACACGGGCCATTTCCACGGGATTACACTGTAGGTAGTCCTTCAACATGAAAAAACAGTTCAGCCAGCCATATTTACGGCCCTGTCTATTCACTTGACTCCAACTTAATTCACAGCGGGGACCTGTAGGCCCGCCGGAGTCGTACTTGATACCACATAGGTCATGACCTTCACCGACGAGAGCCTCTGTCCCAAAGCGGTTCTTCCGCAGAACATCTCGCGATTGGCACAACGATCAGCTGCAATCAACCTATAACCCGAAGTTGCGCCTAGCTAGGGTAAATGGACACATACAACATACGGTTCAATTCACGTGCGCGTCCCCGCACCGCACTCAGGCGTGGGACCTGCACCAACAGTATTTCTCATCATCCAGATTTACGGTCGTACTCCCAGGACGCCGTCAGCCTGCGCGCAGTCTCGTTCGACTGTCTACAGCGTATAAATTGAGCTGCTTAGACCCTAGAGAACTTCCTCCCTCATAAAGACCTGTCCACGTTCAGTTGAAAAAAACCGGCTTTCAATCCTAAGCCATCAATGTATTGAGACATAGGGTGAACAACCGTAACTACAACGCTCCACTACGAAGACGGGACAGGATTAATAT"

for i in range(0, len(s)):
    for n in range (3, 13):
        k = s[i:i+n]
        if (len(k)< n):
            continue
        m = k[::-1]
        
        k=k.replace("A", "Y")
        k=k.replace("T","A")
        k=k.replace("Y","T")
        k=k.replace("C","X")
        k=k.replace("G","C")
        k=k.replace("X","G")
        #print(k + " " + m)
        if k == m:
            print(f"{i+1} {n}")
            #print(k+" " + m)
    
