
s = "CTFGCIGYECSNRGCHGVELFPWLNQCDKQHRTQMWLMQNETYKLNISVFCTEWNPTFPSVGYHKKWMTRIMLDLVPIHCRDQCREHQFHYIINYGVSPFSHWKFRVDAKWVNTLGQMHHKKWYKIYFDYSCDMCDTHKTTFYGHMACQVEKSRLALLMLLFGDPSGPMQYCSYFQDGCIKDSGAENGLFTDSISHFKMIQGYCHVVYEFFSLYWWLLHDCTMDTVFWTITLVLCNWGLAQYTGATAQLFKPTFCASAKSQQIRSQMLSDEPTLAYWMPSGDPEFFSSASMSLCDCSQDPACKRAGYQPPKSVSVPSRQRGKGAFNHNHRSFDCLGAPGAMGQIGVTCHGRMGAVSICIPPYYTTRDKNLMQFCGSYDITVSQMCRMLYKWQSLPCVYSEGDMHSCGNHLCQDAYQCRWVNMQGCLEPSWQYRDWSERNLYRVAHNMHVFTMVSMKTTTQRSWAEVHRIWIRSGIDDEQDQTACSQWQRWIPGAQDKYKIFAFFDKDGCEWNIQFQAYPMPRRCKVDKHPTWKMRLRVAAPNHFRWRFQDNMGDFNEPAIFFWEFWQVHEKNNSWGRVLLTGRYPFNVYPMDWRNASTQRRVRNYLVRTSFVMQGNMLVASYVQEWKQGWLMFQGTIGMFFVGFNDPWHYRVSTGVAGGQQCFKGYKGHTRMTVRWEGCHTRITRDNTSWFKIFGRASNYYSPQMKGETHSINYIVQDMESCQHDHSKSMDTNKNWVMLYDHWPPVYSPSQNQDLWDKSYRAADVIICIWHCHNWRTRYADPACDTNFHASFVGDVAKIPNTRRFVKGE"
massa = 0
for i in s:
    if i == "A":
        massa += 71.03711
    elif i == "C":
        massa += 103.00919
    elif i == "D":
        massa += 115.02694
    elif i == "E":
        massa += 129.04259
    elif i == "F":
        massa += 147.06841
    elif i == "G":
        massa += 57.02146
    elif i == "H":
        massa += 137.05891
    elif i == "I":
        massa += 113.08406
    elif i == "K":
        massa += 128.09496
    elif i == "L":
        massa += 113.08406
    elif i == "M":
        massa += 131.04049
    elif i == "N":
        massa += 114.04293
    elif i == "P":
        massa += 97.05276
    elif i == "Q":
        massa += 128.05858
    elif i == "R":
        massa += 156.10111
    elif i == "S":
        massa += 87.03203
    elif i == "T":
        massa += 101.04768
    elif i == "V":
        massa += 99.06841
    elif i == "W":
        massa += 186.07931
    elif i == "Y":
        massa += 163.06333
    else: 
        print(i)
print(massa)
